netlify/netlify-lambda

lib/serve.js
Resolves https://github.com/netlify/netlify-lambda/issues/2.
=> Match AWS behavior with text content

README.md, bin/cmd.js, lib/build.js, package.json, yarn.lock
This makes netlify-lambda respect any .babelrc in the folder it runs from
It also adds a -c <config> flag for passing an additional webpack config
to the build or serve command
=> Support for customizing babel and webpack

lib/build.js
`additionalConfig` isn't supplied to webpack in `serve`. I assume this isn't intentional since the docs state that `-c` is available to both `build` and `serve`.
=> Pass additionalConfig to webpack while watching

lib/build.js
* Add check to see if source and compiled directories are the same
My confusion was due to the fact that the official [code-examples](https://github.com/netlify/code-examples/tree/b2e70ccf151c3f61b157bf3ee40bc6f29997edbc/function_examples/random-word) repo are incorrect.
The messaging can be updated too, I'm not so good with words.
Closes #7 
Closes #18
=> Warn same source

lib/build.js
On a production lambada, you can access your `netlify.toml` environment variables, but in this package the same isn't available during development, this PR adds the variables from the config on the the `process.env` just like how production works.
* Include `netlify.toml` environment variables
=> Include environment variables from config

lib/serve.js
* Remove `favicon` request logging
* Remove `favicon` errors
Removes these pesky messages from the console:
```
Request from ::1: GET /favicon.ico
Response with status 500 in 0 ms.
Error during invocation:  { Error: Cannot find module '... /favicon.ico'
```
=> Ignore favicon

lib/serve.js
Parity with [aws](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/) async handler support for `netlify-lambda serve`.
=> Support async handlers

lib/build.js
determine node target based on `AWS_LAMBDA_JS_RUNTIME`.
defaults to `6.10` because:
- safety (it's forwards compatible)
- this value was hardcoded before the change
---
question: should `process.env` be counted as env?
=> Custom Babel env target

README.md
This question came up a few times over the last few days.  Adding a note explaining a sound proxy strategy.
=> Add a note regarding proxying

README.md, bin/cmd.js, lib/build.js, package.json, yarn.lock
Thank you for everyone who have contributed issues, and PRs, and thanks for your patience. This is the upgrade that includes everyone's feedback.
Special thanks to @leonardodino for providing a full Babel 7 version in his PR (https://github.com/netlify/netlify-lambda/pull/61)
Supercedes https://github.com/netlify/netlify-lambda/pull/15 and https://github.com/netlify/netlify-lambda/pull/48
Closes https://github.com/netlify/netlify-lambda/issues/35
Closes https://github.com/netlify/netlify-lambda/issues/20
=> Upgrade to Babel 7 and Webpack 4 (fully tested)

lib/serve.js
This small PR sets the size limit of the body parser to match what AWS supports.
=> Match body size limit to AWS

bin/cmd.js, lib/serve.js, package.json
As to be expected, my webpack config / version is incompatible with the `netlify-lambda` package - this option prevents the entire build process and puts the responsibility back on the caller.
Additionally, the require cache is cleared each time the function is called.
By default there is no change in functionality and this change _should_ be completely backwards compatible.
**Usage**
```
npx netlify-lambda serve <folder> -s
```
=> Added "-s --static" option to prevent building of files

lib/serve.js
As the commit suggests.
_Additionally, attempting to parse `undefined` will return an empty object._
=> fixed querystring parsing netlify/netlify-lambda#54

lib/serve.js, package.json, yarn.lock
I haven't read much about the [base-64 package](https://www.npmjs.com/package/base-64) but it's usage in **netlify-lambda** must be incorrect or not doing what's expected.
Switched to node `Buffer` instead and _afaict_ it should be doing the same thing, but for whatever reason `Buffer` works and `base-64` doesn't 🤷‍♂️
#26
=> Removed base-64 package in favour of node Buffer

lib/build.js
Fix #39. I would like to use TypeScript in netlify-lambda!
This PR added for `.ts` and `.mjs` extensions. I changed webpack config.
In order to use TypeScript, you need to install `@babel/preset-typescript` and define `.babelrc` as follows.
```diff
{
"presets": [
+   "@babel/preset-typescript",
[
"@babel/preset-env",
{
"targets": {
"node": "6.10.3"
}
}
]
],
"plugins": [
"@babel/plugin-proposal-class-properties",
"@babel/plugin-transform-object-assign",
"@babel/plugin-proposal-object-rest-spread"
]
}
```
=> Support extensions: .mjs and .ts

lib/build.js
I have a mistake(#76), so I fixed.
* function directory in netlify.toml: `functions/`
* Create file: `src/function.mjs`
* Use this command `netlify-lambda build src/`
Build filename is `functions/function.mjs.js`
Build filename is `functions/function.js`
=> Fix build `.mjs` filename

README.md
Add "how to use TypeScript" section to README.md.
refs #76
=> Add "how to use TypeScript" to README.md

README.md
added documentation to help anyone looking to use netlify-lambda with Angular CLI
=> Add Angular Proxy Documentation

lib/build.js
@sw-yx Please check this.
Fix #79. I add '.ts' to resolve.extensions, so we can use these extensions as import.
refs. https://webpack.js.org/configuration/resolve/#resolve-extensions
in Application directory with lambda
```bash
$ yarn add -D @babel-preset-typescript
$ ../netlify-lambda/bin/cmd.js build src/
```
netlify.toml
```toml
[build]
functions = "functions"
publish = "public"
command = "npm run build"
```
.babelrc
```json
{
"presets": [
"@babel/preset-typescript",
[
"@babel/preset-env",
{
"targets": {
"node": "6.10.3"
}
}
]
],
"plugins": [
"@babel/plugin-proposal-class-properties",
"@babel/plugin-transform-object-assign",
"@babel/plugin-proposal-object-rest-spread"
]
}
```
=> Add .ts to resolve.extensions

lib/serve.js
This fix is related to the issue #54.
Given a request that looks something like this:
```sh
?url=https://www.youtube.com/watch?v=0uwe_PhCRcY&filter[0][field]=title&filter[0][value]=TestElement
```
The value of `event.queryStringParameters` should be an object like this:
```json
{
"url" : "https://www.youtube.com/watch?v=0uwe_PhCRcY",
"filter[0][field]" : "title",
"filter[0][value]" : "TestElement"
}
```
Instead of the following object:
```json
{
"url": "https://m.youtube.com/watch"
}
```
=> Fix 'queryStringParameters' when the url contains multiple question marks

lib/build.js
this PR makes the console output a bit more helpful when you dont have a valid file in your functions folder, e.g you have nested a folder like `functions/hello/hello.js` instead of `functions/hello.js`.
this mistake will cause a cryptic warning like:
```bash
/Users/swyx/Work/hooks-suspense-faunadb-todo/node_modules/netlify-lambda/node_modules/webpack/lib/webpack.js:31
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.entry should be one of these:
function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-emptystring]
-> The entry point(s) of the compilation. …
```
=> Proposal: add warning if no function files found

README.md
Netlify is case-insensitive in its acceptance of the `functions` field in the `netlify.toml` file, but for consistency we're standardizing on all lowercase throughout docs and examples.
Closes #96
=> Make netlify.toml `functions` field consistent

bin/cmd.js
Zero args will respond with --help and invalid/incomplete/unmatched args will respond with an error message (and suggest --help).
ref: #95
=> Provide response for zero/unmatched/invalid args

lib/serve.js, package.json, yarn.lock
Inject decoded information to served function on dev-server as same as production.
Actually it's difficult to verify access_token, so it's only inject decoded information.
but I think that is enough on development to check Netlify identify roles.
=> inject clientContext to served function on dev-server

lib/build.js
=> Check for babelrc up from given functions folder

lib/build.js
=> fix(build): Exclude test files

lib/serve.js
Currently, you must provide a body in the response and a simple status code won't do.
I propose that the body is optional, allowing simple status codes like 300's and 201 to have no body defined.
https://github.com/netlify/netlify-lambda/issues/91
=> Allow reponse body to be optional

bin/cmd.js, lib/serve.js
This PR resolves the issue as described in #45 using Promise.race.
Invocation timeout can be configured using the flag `-t` or `--timeout` with a default of 10 seconds.
=> Enable function invocation timeout using Promise.race

lib/serve.js
This resolves #120 which caused the locally served lambda to crash after its first invocation. This was because the invocation timeout wasn't being cleared, which caused the timeout error handler to call `response.write` after the function was finished. 
This PR resolves the issue by capturing the timeout identifier and calling `clearTimeout` after the `Promise.race` has resolved.
=> Clears the invocation timeout if the invocation is a success.

lib/build.js
This solves https://github.com/netlify/netlify-lambda/issues/119
If a standard NODE_ENV value is specified (production or development), let it pass through and set the mode accordingly. If a non-standard NODE_ENV is specified, let is pass through and set the Webpack mode to none.
=> Fix how NODE_ENV is being handled

lib/build.js
In one of my projects I started to get errors saying that `babel-loader` was not found etc. I could solve this locally by resolving them with `require.resolve`
Could maybe also fix #66
=> Resolve plugins and loaders

package.json
There's some files published to npm that don't have to.
node_modules is slow enough as-is, so i'd encourage everyone to not publish files that are not used anyway.
I added a `files` whitelist to `package.json` to ignore the github configuration and test files.
An alternative would've been `.npmignore`, but once that exists, the `.gitignore` is ignored - so i'd rather do whitelisting via `files` than blacklisting via `.gitignore`.
=> chore: whitelist files published to npm

bin/cmd.js
this logs the `port` the dev server listens to last, after the webpack stats output - e.g.
```bash
$ netlify-lambda serve --config webpack.lambda.js src/functions
netlify-lambda: Starting server
Hash: 01b6293f383c43ad6404
Version: webpack 4.29.6
Time: 2443ms
Built at: 04/16/2019 8:29:24 PM
Asset      Size  Chunks             Chunk Names
graphql.js  1.23 MiB       0  [emitted]  graphql
Entrypoint graphql = graphql.js
[46] ~projects/paderbornjs/site/node_modules/node-fetch/lib/index.mjs 39.6 KiB {0} [built]
[56] ~projects/paderbornjs/site/node_modules/apollo-server-env/dist/index.js 396 bytes {0} [built]
[77] ~projects/paderbornjs/site/node_modules/apollo-server-errors/dist/index.js 5.7 KiB {0} [built]
[78] ~projects/paderbornjs/site/node_modules/graphql-tools/dist/makeExecutableSchema.js …
```
=> refactor: change order of webpack stats logging and server setup

lib/build.js
I came across a need for this today and found this ticket https://github.com/netlify/netlify-lambda/issues/150
=> add bail: true to webpack config

bin/cmd.js
It seems that #141 caused a regression where using the `--static` option in `netlify-lambda serve` no longer started a server. This caused the command to exit immediately.
=> fix: start server when serving static functions

bin/cmd.js
related to issue https://github.com/netlify/netlify-lambda/issues/143
=> clearCache fallbacks to chunk.id if chunk.name is null

.gitignore, README.md, bin/cmd.js, lib/build.js
Based upon this issue https://github.com/netlify/netlify-lambda/issues/152
I'm not sure how this package is tested locally but my process was: 
`yarn add babel-preset-gatsby`
add a .babelrc in the root
```json
{
"presets": ["babel-preset-gatsby"],
}
```
add `functions/handle.js` file with basic lambda 
```javacript
exports.handler = async () => {
return {
statusCode: 200,
body: 'yay'
}
}
```
add `netlify.toml` 
```toml
[build]
functions = "./output"
```
to have the command error run:  `bin/cmd.js build functions/`
You should get and error that looks something along the lines of this: 
```
`babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI.
```
to have the command pass run: `bin/cmd.js build --babelrc false functions/`
I tried that but found that the …
=> Add flag to not use relative .babelrc config

lib/build.js, package.json
User encountered this in #156 (they closed the issue I guess because they were unstuck by a workaround but this PR has the actual fix in).
This commit here;
https://github.com/netlify/netlify-lambda/commit/86332fb40148cb751dcf1a9d486290d730e50074#diff-26b681bd4dac10f25d5293c7595c435bR34
inadvertedly made it mandatory to pass this config in, so users are getting the error as described in #156. This PR just makes that desctructuring a bit more defensive.
Cheers.
=> Fix userWebpackConfig issue

lib/build.js
This PR prioritizes the `module` and `main` fields over the `browser` field, which Webpack uses by default, but is often incompatible with Node.
Closes #138
=> fix: proritize server builds over browser for packages

lib/serve.js
This PR does two things: 
1. It fixes the logic for determining whether to log out the "empty lambda" warning -- there was mistakenly an OR where there should have been an AND. 
2. It bypasses the warning if the `statusCode` is set to `204`, because a `204` response means `no content` and shouldn't have a body (in fact supplying a body for a 204 can cause bugs).
=> fix empty lambda warning

lib/serve.js
Hey, there! Just a typo I noticed and I'd love to fix it! :)
=> fix 404 error typo/grammar

README.md, bin/cmd.js, lib/install.js, package.json, yarn.lock
provide stopgap solution for people who complain its finnicky to install function dependencies.
https://community.netlify.com/t/functions-and-node-modules/2323/6?u=davidwells
https://netlify.slack.com/archives/CGW2Y6XPH/p1565033332089200
=> add install command

README.md
=> improve netlify dev vs netlify lambda docs

lib/install.js
This recognizes the root package.json as well as sub directories containing package.json
closes #174
=> fix: recognize package.json in the root target also

README.md, package.json
Our minimum Node.js version is `8.0.0` due to the `globby` package using that version. We should document it both for our users and the contributors.
=> Document minimum Node.js version

.gitignore
We can't assume `package-lock.json` is part of the user/global `.gitignore` because some libraries push this file to git. So we should add it to `.gitignore`.
=> Add `package-lock.json` to `.gitignore`

lib/build.js
Add a little more explanation to netlify-lambda build error.
This was my first pass at some additional error messaging.
For me it was confusing seeing this error and not knowing I needed to have a separate src and dist directory and that the netlify.toml file only needed to be told about the dist. I assumed netlify-lambda did the build process for you and only needed the src directory.
=> Add extra error messaging

.gitignore, lib/build.js, lib/build.spec.js, package.json
Related to https://github.com/netlify/cli/issues/627#issuecomment-657331256
`netlify-lambda build functions` fails silently if there are complication errors
=> fix(build-command): report exit code 1 when compilation fails

.eslintrc.js, .github/workflows/test.yml, .gitignore, .prettierrc, bin/cmd.js, commitlint.config.js, lib/build.js, lib/build.spec.js, lib/config.js, lib/config.spec.js, lib/install.js, lib/install.spec.js, lib/serve.js, lib/serve.spec.js, package-lock.json, package.json, renovate.json
BREAKING CHANGE: support for node 8 was dropped
Related to https://github.com/netlify/netlify-lambda/issues/240
=> chore: update tooling

lib/build.spec.js, package-lock.json, package.json
Fixes https://github.com/netlify/netlify-lambda/issues/249
Reverted the major version upgrade for `webpack-merge` until I can find a better fix.
According to the [changelog](https://github.com/survivejs/webpack-merge/blob/master/CHANGELOG.md#503--2020-07-06) the `smart` method was dropped and we also need to switch to named imports.
Also added a test case.
=> fix(webpack): use webpack-merge v4 to support merge.smart and node 10

.github/workflows/release-please.yml, CONTRIBUTING.md, package-lock.json, package.json
Updates the release process to use PR releases
=> chore: use release-please action

README.md
Using the .babelrc example from "Using with Typescript" in the README breaks async function.
Error: `{"errorType":"ReferenceError","errorMessage":"regeneratorRuntime is not defined"}`
Relevant issues:
- https://github.com/babel/babel/issues/9849
- https://binyamin.medium.com/enabling-async-await-and-generator-functions-in-babel-node-and-express-71e941b183e2
Fix: Add config object in `@babel/preset-env`
=> Update .babelrc example for use with TS

.github/workflows/release-please.yml, .github/workflows/test.yml
Part of https://github.com/netlify/team-dev/issues/19
This runs the CI on the `latest` Node.js version.
=> chore: run CI on latest Node.js

.github/workflows/test.yml
Fix the tests, by removing node 18 from the workflow. Webpack 4 does not support node 17 and up. So if we want to support node 17 and up we would need to update webpack.
---
For us to review and ship your PR efficiently, please perform the following steps:
🧑‍💻. This ensures we can discuss the changes and get feedback from everyone that should be involved. If you\`re
fixing a typo or something that\`s on fire 🔥 (e.g. incident related), you can skip this step.
passes our tests.
**A picture of a cute animal (not mandatory, but encouraged)**
=> chore: fix tests
